-- 코드를 입력하세요
WITH RANKED AS (
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANKING FROM REST_INFO)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM RANKED
WHERE RANKING = 1
ORDER BY FOOD_TYPE DESC
