-- 코드를 입력하세요
SELECT U.USER_ID, NICKNAME, 
CONCAT(U.CITY,' ',U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS '전체주소',
CONCAT(SUBSTR(TLNO, 1,3),'-',SUBSTR(TLNO, 4,4),'-', SUBSTR(TLNO, 8,4)) AS '전화번호'
FROM USED_GOODS_USER U JOIN (SELECT WRITER_ID, COUNT(BOARD_ID)
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(BOARD_ID) >= 3) AS B ON U.USER_ID = B.WRITER_ID
ORDER BY U.USER_ID DESC