-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, PRODUCT_NAME 
FROM FOOD_PRODUCT F JOIN (
    SELECT CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) M ON F.CATEGORY = M.CATEGORY AND F.PRICE = M.PRICE
ORDER BY F.PRICE DESC